### ISSUE TITLE
Fis calculations in basic.stats and boot.ppfis differ

### ISSUE THREAD

**Issue by pygmyperch** [jgx65/hierfstat#62]
Hi, occasionally I get Fis estimates from basic.stats that are outside the 95% confidence intervals estimated with boot.ppfis. I *think* that it has to do with the sample size correction that is applied in basic.stats, but not used in boot.ppfis? I can try to provide a reproducible example if needed?
Cheers,
Chris

**Comment by jgx65** [comment]
Hi Chris, 

A reproducible example would be great, as `boot.ppfis` uses the results of `basic.stats` to generate the bootstrap confidence intervals. Cheers

**Comment by pygmyperch** [comment]
Hi Jerome,

Attached is an R data file with a Genind object. The code I used is below:

stats <- basic.stats(dat, diploid = TRUE, digits = 4)
Fis <- as.data.frame(stats$Fis)
popFis <- as.data.frame(colMeans(stats$Fis, na.rm = TRUE))

geno.fis <- boot.ppfis(dat)
FisCI <- as.data.frame(geno.fis$fis.ci)

This is a subset of a larger dataset, but in this example I find populations 8 and 11 have lower estimates that the lower CI.
Cheers

[dat.rds.zip](https://github.com/jgx65/hierfstat/files/10061296/dat.rds.zip)

**Comment by jgx65** [comment]
Thanks Chris, the issue comes from estimating FIS as the average of ratios ( `popFis <- as.data.frame(colMeans(stats$Fis, na.rm = TRUE))`) rather than the ratio of averages, which is the correct way of estimating it:

```
dat<-readRDS("dat.rds")
library(hierfstat)
dath<-genind2hierfstat(dat)
bs<-basic.stats(dath)
fis.boot<-boot.ppfis(dath,nboot = 5000)

par(mfrow=c(1,1))
#average of ratios
plot(1:13,colMeans(bs$Fis,na.rm=TRUE),pch=16,col="red",ylim=range(fis.boot$fis.ci))
#ratio of averages
points(1:13,1-colSums(bs$Ho,na.rm=TRUE)/colSums(bs$Hs,na.rm=TRUE),col="orange",pch=16)
segments(1:13,fis.boot$fis.ci$ll,1:13,fis.boot$fis.ci$hl,col="orange")

```

In the code for the figure above, the ratio of averages in orange is always in the center of the CI, while the average of ratio (in red)  is not.  If you absolutely want the average of ratios (lots of literature around as to why it's not appropriate, see help page of `basic. stats` for instance, or WC84), you'll need to modify the code of `boot.ppfis`  to calculate the average of Fis rather than the 1-mean(Ho)/mean(Hs).  

Hope this helps

**Comment by pygmyperch** [comment]
Many thanks, Jerome. That was embarrassingly obvious...
